###
GET http://localhost:4004/odata/v4/nautical/VOYTYP

###POST REQUEST
POST http://localhost:4004/odata/v4/nautical/VOYTYP
Content-Type: application/json

{
    "VOYCD":"1236",
    "VOYDES":" CHARTER  jijuh333"
}

###PATCH VOYAGE

PATCH http://localhost:4004/odata/v4/nautical/VOYTYP/1236
Content-Type: application/json

{
    "VOYCD":"1236",
    "VOYDES":"SPECIAL CHARTER  changed 3rd"
}
